FROM cirrusci/flutter:stable

WORKDIR /app

COPY . .

RUN flutter pub get

# Это для запуска тестов или CLI-команд
# RUN flutter test

# Можно запустить напрямую flutter web сервер, если хочешь (не продакшен)
CMD ["flutter", "run", "-d", "web-server", "--web-port=8080", "--web-hostname=0.0.0.0"]
