version: '3.9'



services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schedule_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  user_service:
      build:
        context: ./user_service
      ports:
        - "8001:8000"
      depends_on:
        - db
      environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/userdb


  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/schedule_db

volumes:
  pgdata:
